repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: unasync
        name: unasync
        entry: dev-scripts/make-unasync
        language: system
        files: "^(neomodel/_async|test/async_)/.*"